[gmail]
email = "drwisyirfnnn@gmail.com@gmail.com"             # Replace with your Gmail address for sending OTPs
app_password = "Cbt87008700_"   # Replace with your Gmail App Password (not your normal password)

[login]
username = "drwisyirfnnn"       # Replace with the username you want for logging into the dashboard
password = "Cbt87008700_"       # Replace with the password you want for logging in
